//! Domain layer: what relay is, independent of any harness or CLI.

pub mod agents_md;
pub mod audit;
pub mod bench;
pub mod bootstrap;
pub mod brief;
pub mod budget;
pub mod claims;
pub mod collide;
pub mod compile;
pub mod condense;
pub mod exec;
pub mod handoff;
pub mod index;
pub mod likely;
pub mod log;
pub mod memory;
pub mod okf;
pub mod outline;
pub mod outputs;
pub mod paths;
pub mod read_guard;
pub mod reads;
pub mod scoreboard;
pub mod spool;
pub mod task_brief;
pub mod timings;
pub mod usage;
